function initiatePayment(uuid) {
    window.payfast_do_onsite_payment({
        uuid: uuid, // The UUID generated by your backend
        cancel_url: ' http://127.0.0.1:5501/user-app/client/public/checkout_order.html       ',
        return_url: 'http://127.0.0.1:5501/user-app/client/public/checkout_order.html?paid=true      '
    });
}
